### ISSUE TITLE
How the module signature is constructed for mod. is not explained

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-TSconfig#126]
https://docs.typo3.org/m/typo3/reference-tsconfig/master/en-us/PageTsconfig/Mod.html

There are only very simple examples on this page which use `mod.web_info` etc. If you created your own be modules in an extension, it is not so intuitive, what is to be used here.

How is this key constructed, e.g. 

1.  `MAINMODULEKEY UNDERLINE  SUBMODULEKEY`), e.g. 'web_info', 'web_layout', 'site_configuration', 'system.config'
2.  MAINMODULEKEY UNDERLINE EXTKEY_IN_CAMEL_CASE SUBMODULEKEY_STARTING_WITH_CAPITAL_LETTER  e.g. 'web_FormFormbuilder', is created by using:

```
\TYPO3\CMS\Extbase\Utility\ExtensionUtility::registerModule(
    'TYPO3.CMS.Form',
    'web',
    'formbuilder',
```

So in this example, the lowercase 'formbuilder' is converted to CamelCase 'Formbuilder' and the extension key is also converted to CamelCase and directly prepended before the submodule key.

It's weird that in the examples :one: after the underline, it is all-lowercase, while in  :two:, it is CamelCase, this makes it not so intuitive.

I would assume, that the modules for the first case are created with `addModule()`, while the ones for the second are created with `registerModule()` (Extbase)

Possibly link to "[Naming conventions](https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ExtensionArchitecture/BestPractises/NamingConventions.html)" and add the information there.

**Comment by anubhasy** [comment]
Hi @sypets I want to help with updating the document. However, I do need some initial help in getting started with this. Can you point me to the right direction?

**Comment by sypets** [comment]
@anubhasy 

For minor changes, hit the "Edit on GitHub" page and make your changes. You can find a detailed walkthrough here: https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingDocsOfficial/GithubMethod.html

For larger changes, you might want to make the changes locally and also test the rendering locally, see https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingDocsOfficial/LocalEditing.html

In any case, it is recommended to join the TYPO3 Slack workspace and the `#typo3-documentation` channel on Slack, see https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/HowToGetHelp.html

You can ask questions on Slack, ask for help or - for bigger changes - announce what you plan to do and get feedback.

**Comment by sypets** [comment]
@anubhasy I am not sure if I answered your question. I assumed you needed help with the workflow but I saw that you already contributed. I am also not sure what your level of expertise in TYPO3 is. 

This issue here may not be a good fit for you. It has been sitting idly for a while and I am not even sure if the information above is up to date. If you are looking for tasks that are a good fit, I would also recommend to come to the Slack workspace. You can also find some ideas here: https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingDocsOfficial/HowYouCanHelp.html

**Comment by anubhasy** [comment]
Thanks for responding @sypets. What I was trying to ask is how to contribute to this issue, but I think it would be best for me to discuss the areas of contribution in the Slack workspace. 
I am trying to join the Slack Workspace but registering for the Typo3 account is taking a lot of time. It's not letting me login yet... maybe it needs admin approval before I can login. I will surely ping you as soon as my registration is approved.

**Comment by linawolf** [comment]
@anubhasy did you succeed in joining slack yet?

**Comment by sypets** [comment]
I would like to close this issue now. 

I added a PR for clarification in TYPO3 Explained, but I don't think the module signature should be explained here, on the page mod.
