### ISSUE TITLE
Add information for clearCacheCmd

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-TSconfig#140]
https://docs.typo3.org/m/typo3/reference-tsconfig/master/en-us/PageTsconfig/TceMain.html

* I found that news has a different way of doing this -  but with news doing this is not necessary and perhaps we should add a note that this may not exactly be the "best" practice - and it may depend on the extension? 

https://docs.typo3.org/p/georgringer/news/master/en-us/AdministratorManual/BestPractice/ClearCache/Index.html

The problem is you have to add these TSconfig on every page with records manually.

**Comment by liayn** [comment]
I don't understand your text above. Can your rephrase please?
What has news to do with this?

**Comment by sypets** [comment]
Sorry, I was on the wrong page before. I changed the text.

News uses a different mechanism to ensure the clearing of cache which makes the use of the TSconfig unnecessary. 

But I am not sure if that should be mentioned there because it will clutter up the page. Closing.

**Comment by liayn** [comment]
> News uses a different mechanism to ensure the clearing of cache which makes the use of the TSconfig unnecessary.

News uses the default mechanism of the Core. DataHandler flushes all caches by a tag named `<table_name>:<uid>`. So news simply applies the currently displayed news to the cache tags of the current page, so it gets flushed once a news entry is modified.

This feature here is mainly used for things like content stored on a dedicated page, which is then included in all other pages (i.e. header or footer) with TypoScript. Changing this shared content requires all pages' cache to be flushed.
