### ISSUE TITLE
Changed condition syntax; Conditions in TSconfig

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/TYPO3CMS-Reference-TSconfig#157]
Check if the following examples still work or need to be changed:

https://docs.typo3.org/m/typo3/reference-tsconfig/master/en-us/UsingSetting/Index.html#condition-references

**Comment by kitzberger** [comment]
@linawolf, I've just had a look at whether `[tree.level = X]` is working as `[treeLevel = X]` used to do for PageTS. We usually use this to show certain fields only on site root level, e.g. `is_siteroot`, `backend_layout` and `backend_layout_next_level`.

Hide certain fields globally:
```
TCEFORM.pages.is_siteroot.disabled = 1
TCEFORM.pages.backend_layout.disabled = 1
TCEFORM.pages.backend_layout_next_level.disabled = 1
```

But show them on root pages (**old syntax**):
```
[treeLevel = 0]
TCEFORM.pages.is_siteroot.disabled = 0
TCEFORM.pages.backend_layout.disabled = 0
TCEFORM.pages.backend_layout_next_level.disabled = 0
[global]
```

Which translates to the **new syntax**:
```
[tree.level == 1]
TCEFORM.pages.is_siteroot.disabled = 0
TCEFORM.pages.backend_layout.disabled = 0
TCEFORM.pages.backend_layout_next_level.disabled = 0
[global]
```

As you can see, there's a difference in what's considered to treelevel 0. In my opinion that's a bug.

Another thing is that for nested sites the treelevel is not reset even though there's a sys_template record with `root=1` set that is processed correctly in FE TypoScript.

So to make the snippet work for PageTS we gotta use this for a root site that's located on absolute treelevel 3:

```
[tree.level == 4]
TCEFORM.pages.is_siteroot.disabled = 0
TCEFORM.pages.backend_layout.disabled = 0
TCEFORM.pages.backend_layout_next_level.disabled = 0
[global]
```

**Comment by linawolf** [comment]
@kitzberger did you make an issue on https://forge.typo3.org/projects/typo3cms-core/issues about this? This sounds like a bug indeed

**Comment by kitzberger** [comment]
@linawolf, not yet, but now: https://forge.typo3.org/issues/96385

**Comment by linawolf** [comment]
I will close this until the Core Issue is resolved
