### ISSUE TITLE
Documentation claims TCEFORM.[table].[field].disabled renders as readOnly, but actually does not render.

### ISSUE THREAD

**Issue by LeoniePhiline** [TYPO3-Documentation/TYPO3CMS-Reference-TSconfig#182]
https://docs.typo3.org/m/typo3/reference-tsconfig/9.5/en-us/PageTsconfig/TceForm.html#disabled

Quoting the intro:
> If set, the field is rendered, but not editable by the user.

Quoting the code example:
> `# The title field of the pages table is not editable`

However, in reality, TYPO3 returns early without rendering the field, instead of rendering it as `readOnly`:

https://github.com/TYPO3/typo3/blob/master/typo3/sysext/backend/Classes/Form/Container/SingleFieldContainer.php#L88-L90

**Comment by linawolf** [comment]
@LeoniePhiline thanks for pointing this out, I made a PR for it
