### ISSUE TITLE
Usage of settings from site configuration YAML file in Page TSconfig

### ISSUE THREAD

**Issue by FelHell** [TYPO3-Documentation/TYPO3CMS-Reference-TSconfig#190]
[Feature: #91080 - Site settings as TypoScript constants and in TSconfig](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4/Feature-91080-SiteSettingsAsTsConstantsAndInTsConfig.html) added the possibility to define constants in the YAML file of the site configuration. This feature should be added to the Page TSconfig section.

**Comment by linawolf** [comment]
Is already merged
