### ISSUE TITLE
No way to inspect UserTSconfig anymore

### ISSUE THREAD

**Issue by cweiske** [TYPO3-Documentation/TYPO3CMS-Reference-TSconfig#28]
The section [Verifying the final configuration](https://docs.typo3.org/typo3cms/TSconfigReference/UserTsconfig/Field/Index.html#userverifyingthefinalconfiguration) tells me to view the user's TSconfig in the "Tools -> User Admin" module.

In TYPO3 6.2 and 7.6 the "compare" view does not show  the typoscript configuration.

**Comment by Chrissitopher** [comment]
The compare feature is no longer showing the TSconfig field. This useful function has been removed with commit 57a3cb396a1a01b831672c533656b3c1d6cd2d25.

I'll update the information to become correct again.
