### ISSUE TITLE
Single UserTsconfig/Options not linkable / have no anchor/ID

### ISSUE THREAD

**Issue by cweiske** [TYPO3-Documentation/TYPO3CMS-Reference-TSconfig#34]
I wanted  to create a link to a specific option on On https://docs.typo3.org/typo3cms/TSconfigReference/UserTsconfig/Options/Index.html, `createFoldersInEB` - but it does not have an ID that I could use to link to.

**Comment by marble** [comment]
Now you can, at least on that page: https://docs.typo3.org/typo3cms/TSconfigReference/UserTsconfig/Options/Index.html#createfoldersineb

It required quite a bit of editing ... Thanks for asking: All interaction brings the documentation forward.
