### ISSUE TITLE
options.hideRecords.[table]

### ISSUE THREAD

**Issue by OttoAndras** [TYPO3-Documentation/TYPO3CMS-Reference-TSconfig#52]
I made some tests today with this option because its functionality would be just perfect to my current project. 
The problem is that this option is not generic. It works only with the "pages" table and not with any other table what the documentation suggest. 
It seems that it was maybe planned as a generic solution, but it is not implemented in the current latest.

I think that the [table] should simply be "pages" as in the example; otherwise it is not correct atm.

**Comment by Chrissitopher** [comment]
That is correct: Only options.hideRecords.pages is evaluated, nothing else. See https://github.com/TYPO3/TYPO3.CMS/search?utf8=%E2%9C%93&q=hideRecords&type=.
